export const FETCH_TESTS = 'FETCH_TESTS'
export const ADD_TEST = 'ADD_TEST'
export const TEST_FETCHED = 'TEST_FETCHED'
export const DELETE_TEST = 'DELETE_TEST'
export const UPDATE_TEST= 'UPDATE_TEST'

export const ADD_QUESTION = 'ADD_QUESTION'
export const DELETE_QUESTION = 'DELETE_QUESTION'

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

export const SET_CURRENT_USER  = 'SET_CURRENT_USER'
